### ISSUE TITLE
missed link in wiki  

### ISSUE THREAD

**Issue by sepu85** [1Hive/wiki#9]
when clicking on
> You can interact with these contracts through the Aragon Client interface at [aragon.1hive.org](https://aragon.1hive.org/#/0xe9869a0bbc8fb8c61b7d81c33fa2ba84871b3b0e) 

The given address (https://aragon.1hive.org/#/0xe9869a0bbc8fb8c61b7d81c33fa2ba84871b3b0e) shows the following error:

![image](https://user-images.githubusercontent.com/22507864/105882253-bacc8280-6005-11eb-8d76-63d36a324b42.png)

**Comment by onbjerg** [comment]
Hi, sorry for the delayed response!

If you hadn't figured out by now, this is simply just because you were not on the xDai network, so it tried to resolve the organization from mainnet.

See [here](https://wiki.1hive.org/guides/xdai#connecting-via-metamask) on how to connect to xDai :)

**Comment by sepu85** [comment]
lol! long time! yeah, probably was that! I don´t remember, thanks!! 😊
